services:
  project-zomboid:
    image: thunderzstrike/project-zomboid:latest
    environment:
      ADMINPASSWORD: 'passwd'
      CACHEDIR: '/home/steam/Zomboid'
      STEAMAPP: 'pz'
      MEMORY: '4096m'
      SERVERNAME: 'pz-server'
      STEAMAPPBRANCH: 'unstable'
      FORCEUPDATE: 1 # Recommended if you have workshop items
      UID: 1000
      GID: 1000
    ports:
      - "16261:16261/udp"
      - "16262:16262/udp"
      - "27015:27015/tcp"
    volumes:
      - pz-data:/home/steam/Zomboid
      - pz-server:/home/steam/pz
volumes:
  pz-data:
  pz-server:
